##' @title volcano
##' @description This function would plot volcano based on DESeqRes output and save as pdf and png format
##' @param de_res a dataframe which would be generated by DESeqRes function
##' @param filename NULL or character, the prefix of output. When value is NULL, the figures are not saved.
##' @param output_dir the path of the directory to save plot
##' @param fold_change a character, the colname of log2(Fold Change) in de_res
##' @param adj_pvalue a character, the colname of adjusted P-value in de_res
##' @param de_class a character, the colname of differential expression type in de_res
##' @param fold_change_line a numeric, the threshold of significant log2(fold change)
##' @param adj_pvalue_line a numeric, the threshold of significant adjusted P-value
##' @return NULL
##' @examples
##' \dontrun{
##' input = create_count_phe()
##' dds = create_DEseq(input[[1]],input[[2]],ref_level="untreated")
##' res = DESeq_res(dds)
##' volcano(res)
##' }
##' @import ggplot2
##' @importFrom grDevices pdf png dev.off
##' @export
##'
volcano <- function(de_res,filename=NULL,output_dir=".",fold_change="log2FoldChange",adj_pvalue="padj",de_class="regulate",fold_change_line=1,adj_pvalue_line=0.05){
  stopifnot(class(de_res)[1]=="data.frame" & all(c(fold_change,adj_pvalue,de_class)%in%colnames(de_res)))
  g <- ggplot(data=de_res,aes(x=.data[[fold_change]],y=-log10(.data[[adj_pvalue]]),colour=factor(.data[[de_class]]))) +
    geom_point() +
    geom_hline(yintercept=-log10(adj_pvalue_line),linetype=4)+
    geom_vline(xintercept=c(-fold_change_line,fold_change_line),linetype=4)
  p <- g+scale_size_identity()+
    scale_color_manual(values =c("green","black","red"))+ #"green","black","red" is responding to factor(DEres$de_class), which is "Down","Normal","Up"
    xlab("log2(Fold Change)")+ylab("-log10(FDR)")+labs(color="regulate")+
    theme_classic()+
    theme(axis.title=element_text(size=15),legend.title = element_text(size=15),legend.text = element_text(size=12),axis.text = element_text(size=rel(1.5)))

  if(!is.null(filename)){
    ggsave(filename=filename,plot=p,path=output_dir)
  }

  return(p)
}
